spring:

  devtools:
    livereload:
      enable: true
    freemarker:
      cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ec2-54-208-139-247.compute-1.amazonaws.com:5432/dtdhnlb4gji1r
    username: kkrnopyiwxiaxa
    password: 5911a00f9d1beb960254a8eb14d26996dbded1aaa2badb43892b8f6ec3482ed9
    port : 5432

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: ${PORT:8080}
