spring:

  devtools:
    livereload:
      enable: true
    freemarker:
      cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ec2-54-208-139-247.compute-1.amazonaws.com:5432/dtdhnlb4gji1r
    username: wrcpnufopkurww
    password: 131ead0abee1ed0e40c486eec71fe841e1f460637711b4c2794986debf7ae054
    port : 5432

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: ${PORT:8080}
