spring:

  devtools:
    livereload:
      enable: true
    freemarker:
      cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ec2-34-194-171-47.compute-1.amazonaws.com:5432/d2gahh24316ib1
    username: hwhlpduznogces
    password: 08d21dbaa9f46fdf722f3a721db600c380a1f190bbf32f0eb33853b468d70dc9
    port : 5432

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port=${PORT:8080}:
