spring:

  devtools:
    livereload:
      enable: true
    freemarker:
      cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-157-15-228.compute-1.amazonaws.com:5432/d2ppbsnlgvpk55
    username: hebbyplnpkgrxe
    password: dd2ecec616e15dc75cd45390b55121ff33e41a8d8371b4303264eda3f21d4fcc
    port : 5432

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: ${PORT:8080}
